apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-db
spec:
  # serviceName: provider-db
  selector:
    matchLabels:
      app: provider-db
  template:
    metadata:
      labels:
        app: provider-db
    spec:
      containers:
      - name: provider-db
        image: mongo
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data/db"
            name: provider-claim
      volumes:
        - name: provider-claim
          persistentVolumeClaim:
              claimName: provider-claim