version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-auth
    image: alcatraz_auth:latest
    ports:
    - "8082:8082"
    links:
      - "db"
  db:
    image: mongo
    hostname: db
    volumes:
      - "mongodb_data:/data/db"
    ports:
    - "27017:27017"

volumes:
  mongodb_data:
    external: true
