apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-claim
  namespace: default
spec:
  storageClassName: auth
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi