apiVersion: v1
kind: PersistentVolume
metadata:
  name: provider-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: provider
  hostPath:
    path: "/data/provider"